[template.environment]
  AUTHOR_NAME = "Your Name"
  AUTHOR_EMAIL = "Your email address"
  SITE_TITLE = "Website name"
  SITE_DESCRIPTION = "Website description"
  GITHUB_TOKEN = "Access token from Github with 'repo' permissions"

[[plugins]]
package = "netlify-plugin-inline-functions-env"
  [plugins.inputs]
  buildEvent = "onBuild"

[functions]
  directory = "functions"

[[redirects]]
  from = "/11ndieweb/:function"
  to = "/.netlify/functions/11ndieweb"
  status = 200
[[redirects]]
  from = "/activitypub/:function"
  to = "/.netlify/functions/activitypub"
  status = 200
[[redirects]]
  from = "/.well-known/host-meta*"
  to = "https://fed.brid.gy/.well-known/host-meta:splat"
  status = 302
[[redirects]]
  from = "/.well-known/webfinger*"
  to = "https://fed.brid.gy/.well-known/webfinger"
  status = 302